FROM ubuntu:22.10

RUN apt-get -y update

# install git
RUN apt-get -y install git

# install golang
RUN apt-get -y install golang

# install geth
RUN apt-get -y install openssl libssl-dev libclang-dev libudev-dev cmake gcc g++ pkg-config file file
RUN git clone https://github.com/ethereum/go-ethereum
RUN cd go-ethereum && \
    make geth

ENV PATH="/go-ethereum/build/bin:${PATH}"

RUN mkdir /data

CMD geth console --datadir "/data"